[package]
name = "libgmtr"
version = "0.1.1"
edition = "2021"
license = "MIT"
description = "Rust crate to calculate the gematria value of letters and words"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
